services:

  agent:
    build:
      context: ./agent
      dockerfile: Dockerfile
    container_name: agent
    networks:
      - project-network
    volumes:
      - ./agent:/agent
      - ./workspace:/workspace
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - WORKING_DIR=/workspace
    depends_on:
      - ollama
    working_dir: /agent
    command: sleep infinity
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./workspace
          target: /workspace
        - action: rebuild
          path: ./agent/Dockerfile

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
    depends_on:
      data-base:
        condition: service_healthy
    networks:
      - project-network
    volumes:
      - ./ollama-data:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=30m
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: unless-stopped

  data-base:
    image: postgres:16.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - project-network
    volumes:
      - data-base-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped

volumes:
  data-base-data:
  ollama-data:
    driver: local

networks:
  project-network:
    driver: bridge

